### ISSUE TITLE
Outdated translations

### ISSUE THREAD

**Issue by piotrdrag** [fedora-sysv/chkconfig#1]
Translations haven’t been updated in 4 years. It would be great if you could regularly push/pull translations to/from <https://fedora.zanata.org/project/view/chkconfig>.

**Comment by lnykryn** [comment]
@piotrdrag Hi, I have prepared a pull request with new translation from zanata. SInce I've never done that before, could you do a small sanity check for that?

**Comment by piotrdrag** [comment]
It looks fine, as far as I can tell. I see that you also pushed a new POT file to Zanata — remember to pull new translations before the next release. :)
