### ISSUE TITLE
alternatives.8 manual inconsistency for "--list"

### ISSUE THREAD

**Issue by crawley** [fedora-sysv/chkconfig#11]
There is an inconsistency in the manual page for alternatives.  According to the synopsis section, the "--list" option can be followed by a <name>  argument.  But further on, description of "--list" disagrees, and so does the code; e.g. "alternatives --help".

**Comment by lnykryn** [comment]
https://github.com/fedora-sysv/chkconfig/pull/12 should fix this.

**Comment by lnykryn** [comment]
Fixed
