### ISSUE TITLE
DIR handle is not closed after use

### ISSUE THREAD

**Issue by zr000** [fedora-sysv/chkconfig#22]
https://github.com/fedora-sysv/chkconfig/blob/6b784260ef5e960a536540d9bdfad39b621783e3/ntsysv.c#L372

**Comment by lnykryn** [comment]
Is that an issue? I think this function is not called in a loop and ntsysv is a short-lived process.

**Comment by zr000** [comment]
ok, I use it in my thread for parse service info ^_^

**Comment by lnykryn** [comment]
Hmm if you are using xinetd, then there is probably nothing better. But if you are not using it and you are interested in information about initscripts and systemd units, then please just use the systemd dbus api
