### ISSUE TITLE
Do not hardcode systemd dir

### ISSUE THREAD

**Issue by tpgxyz** [fedora-sysv/chkconfig#23]
In Makefile you are hardcoding systemd dir to $(DEST)/usr/lib/systemd.

Not all distributions install systemd into /usr/lib.

**Comment by jamacku** [comment]
Hi Tomasz,
thank you for your contribution. I'll release your patch in next release of chkconfig.

Jan

**Comment by tpgxyz** [comment]
@jamacku Thanks.
