### ISSUE TITLE
mem leak in alternatives

### ISSUE THREAD

**Issue by JackFangXN** [fedora-sysv/chkconfig#24]
i find memory leak in alternatives.c when using AddressSanitizer.the leak main about reallca, strdup, just few bytes. but multiple code leaks. so i can't not decide to modify it or not, i want to know what does github give suggestion about this issue.

Version: 1.10
=================================================================
==8212==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f2ab5ab in realloc (/lib64/libasan.so.4+0xd35ab)
    #1 0xaaaac8c65e73  (/usr/sbin/alternatives+0x7e73)
    #2 0xaaaac8c68437  (/usr/sbin/alternatives+0xa437)
    #3 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c6759b  (/usr/sbin/alternatives+0x959b)
    #2 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c684df  (/usr/sbin/alternatives+0xa4df)
    #2 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c68e1b  (/usr/sbin/alternatives+0xae1b)
    #2 0xaaaac8c66d07  (/usr/sbin/alternatives+0x8d07)
    #3 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c68e1b  (/usr/sbin/alternatives+0xae1b)
    #2 0xaaaac8c66b63  (/usr/sbin/alternatives+0x8b63)
    #3 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c68d4b  (/usr/sbin/alternatives+0xad4b)
    #2 0xaaaac8c66d07  (/usr/sbin/alternatives+0x8d07)
    #3 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 45 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c68d4b  (/usr/sbin/alternatives+0xad4b)
    #2 0xaaaac8c66b63  (/usr/sbin/alternatives+0x8b63)
    #3 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f2ab5ab in realloc (/lib64/libasan.so.4+0xd35ab)
    #1 0xaaaac8c66cbb  (/usr/sbin/alternatives+0x8cbb)
    #2 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c66e07  (/usr/sbin/alternatives+0x8e07)
    #2 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c68db3  (/usr/sbin/alternatives+0xadb3)
    #2 0xaaaac8c66d07  (/usr/sbin/alternatives+0x8d07)
    #3 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0xffff9f218f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac8c68db3  (/usr/sbin/alternatives+0xadb3)
    #2 0xaaaac8c66b63  (/usr/sbin/alternatives+0x8b63)
    #3 0xffff9f072adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac8c68777  (/usr/sbin/alternatives+0xa777)

SUMMARY: AddressSanitizer: 364 byte(s) leaked in 11 allocation(s).
NEW	link: link_a	Prio: 10	Family: family_a

=================================================================
==8255==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7c035ab in realloc (/lib64/libasan.so.4+0xd35ab)
    #1 0xaaaac5949647  (/usr/sbin/alternatives+0x7647)
    #2 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5948fcf  (/usr/sbin/alternatives+0x6fcf)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594c4df  (/usr/sbin/alternatives+0xa4df)
    #2 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594b59b  (/usr/sbin/alternatives+0x959b)
    #2 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7c035ab in realloc (/lib64/libasan.so.4+0xd35ab)
    #1 0xaaaac594811f  (/usr/sbin/alternatives+0x611f)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7c031db in __interceptor_malloc (/lib64/libasan.so.4+0xd31db)
    #1 0xaaaac594849f  (/usr/sbin/alternatives+0x649f)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7c031db in __interceptor_malloc (/lib64/libasan.so.4+0xd31db)
    #1 0xaaaac59493b7  (/usr/sbin/alternatives+0x73b7)
    #2 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7c035ab in realloc (/lib64/libasan.so.4+0xd35ab)
    #1 0xaaaac594acbb  (/usr/sbin/alternatives+0x8cbb)
    #2 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 13 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59484e7  (/usr/sbin/alternatives+0x64e7)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59481ef  (/usr/sbin/alternatives+0x61ef)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594897b  (/usr/sbin/alternatives+0x697b)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594ce1b  (/usr/sbin/alternatives+0xae1b)
    #2 0xaaaac594ad07  (/usr/sbin/alternatives+0x8d07)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5948217  (/usr/sbin/alternatives+0x6217)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594ce1b  (/usr/sbin/alternatives+0xae1b)
    #2 0xaaaac594ab63  (/usr/sbin/alternatives+0x8b63)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5948147  (/usr/sbin/alternatives+0x6147)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5948b57  (/usr/sbin/alternatives+0x6b57)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594cd4b  (/usr/sbin/alternatives+0xad4b)
    #2 0xaaaac594ad07  (/usr/sbin/alternatives+0x8d07)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 45 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5947fb3  (/usr/sbin/alternatives+0x5fb3)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 45 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59483eb  (/usr/sbin/alternatives+0x63eb)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 45 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594cd4b  (/usr/sbin/alternatives+0xad4b)
    #2 0xaaaac594ab63  (/usr/sbin/alternatives+0x8b63)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594ae07  (/usr/sbin/alternatives+0x8e07)
    #2 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59486af  (/usr/sbin/alternatives+0x66af)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594cdb3  (/usr/sbin/alternatives+0xadb3)
    #2 0xaaaac594ad07  (/usr/sbin/alternatives+0x8d07)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5948093  (/usr/sbin/alternatives+0x6093)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5948abb  (/usr/sbin/alternatives+0x6abb)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594cdb3  (/usr/sbin/alternatives+0xadb3)
    #2 0xaaaac594ab63  (/usr/sbin/alternatives+0x8b63)
    #3 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac5948037  (/usr/sbin/alternatives+0x6037)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0xffffa7b70f63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac594842b  (/usr/sbin/alternatives+0x642b)
    #2 0xaaaac594923f  (/usr/sbin/alternatives+0x723f)
    #3 0xaaaac594c437  (/usr/sbin/alternatives+0xa437)
    #4 0xffffa79caadf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #5 0xaaaac594c777  (/usr/sbin/alternatives+0xa777)

SUMMARY: AddressSanitizer: 877 byte(s) leaked in 28 allocation(s).
NEW	link: link_b	Prio: 20	Family: family_b

=================================================================
==8301==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0xffffa55f15ab in realloc (/lib64/libasan.so.4+0xd35ab)
    #1 0xaaaac59f72d3  (/usr/sbin/alternatives+0x62d3)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Direct leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7fcf  (/usr/sbin/alternatives+0x6fcf)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59fa59b  (/usr/sbin/alternatives+0x959b)
    #2 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59fb4df  (/usr/sbin/alternatives+0xa4df)
    #2 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #3 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0xffffa55f15ab in realloc (/lib64/libasan.so.4+0xd35ab)
    #1 0xaaaac59f711f  (/usr/sbin/alternatives+0x611f)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Direct leak of 26 byte(s) in 2 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f74e7  (/usr/sbin/alternatives+0x64e7)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59fbb4b  (/usr/sbin/alternatives+0xab4b)
    #2 0xaaaac59fa0ef  (/usr/sbin/alternatives+0x90ef)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f71ef  (/usr/sbin/alternatives+0x61ef)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f797b  (/usr/sbin/alternatives+0x697b)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 92 byte(s) in 2 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7b57  (/usr/sbin/alternatives+0x6b57)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 90 byte(s) in 2 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f73eb  (/usr/sbin/alternatives+0x63eb)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0xffffa55f11db in __interceptor_malloc (/lib64/libasan.so.4+0xd31db)
    #1 0xaaaac59f749f  (/usr/sbin/alternatives+0x649f)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7bd7  (/usr/sbin/alternatives+0x6bd7)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 47 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7217  (/usr/sbin/alternatives+0x6217)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7147  (/usr/sbin/alternatives+0x6147)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 45 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f6fb3  (/usr/sbin/alternatives+0x5fb3)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 18 byte(s) in 2 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f76af  (/usr/sbin/alternatives+0x66af)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 12 byte(s) in 2 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7abb  (/usr/sbin/alternatives+0x6abb)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 10 byte(s) in 2 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f742b  (/usr/sbin/alternatives+0x642b)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7093  (/usr/sbin/alternatives+0x6093)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0xffffa555ef63 in strdup (/lib64/libasan.so.4+0x40f63)
    #1 0xaaaac59f7037  (/usr/sbin/alternatives+0x6037)
    #2 0xaaaac59fa95b  (/usr/sbin/alternatives+0x995b)
    #3 0xffffa53b8adf in __libc_start_main (/lib64/libc.so.6+0x20adf)
    #4 0xaaaac59fb777  (/usr/sbin/alternatives+0xa777)

**Comment by lnykryn** [comment]
Meh, alternatives is a short-lived process, so the memory leaks are not an issue.

**Comment by JackFangXN** [comment]
tks, short-lived process will be automatic recycling resources when process life is dead. so i also think that could not care.
