### ISSUE TITLE
Make alternatives state dir configurable (or move it from /var to /etc)

### ISSUE THREAD

**Issue by LorbusChris** [fedora-sysv/chkconfig#27]
This is e.g. necessary when running on an rpm-ostree based system 

For more context, see:
https://bugzilla.redhat.com/show_bug.cgi?id=1657367
https://github.com/coreos/fedora-coreos-config/pull/264#issuecomment-573104158

**Comment by dustymabe** [comment]
Any chance we could make progress on this issue? Getting alternatives working properly on ostree systems would be very useful and save a lot of time when debugging.

**Comment by Conan-Kudo** [comment]
This is a duplicate of #9.

**Comment by LorbusChris** [comment]
Closing as duplicate
