### ISSUE TITLE
/usr/sbin/alternatives needs to support more inclusive terminology

### ISSUE THREAD

**Issue by netsnipe** [fedora-sysv/chkconfig#80]
Per the IETF's [draft-knodel-terminology](https://datatracker.ietf.org/doc/draft-knodel-terminology/) memo and [Inclusive Naming Initiative](https://inclusivenaming.org/faqs/#what-terms-are-we-recommending-you-consider) (of which the Linux Foundation and Red Hat are both members of), please consider deprecating the use of "`master/slave`" terminology in this program and replacing them with a more inclusive pair like "`leader/follower`".

Given that there will be some use-cases or scripts out there that will rely on `alternatives` current behaviour and parameters for years to come, I'm under no illusion that compatibility/legacy shims will be around for years if not a decade or more to come.

**Comment by jamacku** [comment]
Thank you @netsnipe for your request, I'm taking it into consideration. But since we have now different priorities, it might take some time.
