### ISSUE TITLE
"Could not merge the repository" on Fedora Weblate

### ISSUE THREAD

**Issue by middlingphys** [fedora-sysv/chkconfig#93]
The message mentioned in the title is shown on this page.
https://translate.fedoraproject.org/projects/fedora-sysv/chkconfig/

It seems to be caused by the branch name change from "master" to "main". Same problem is discussed here and can be resolved by changing the Fedora Weblate settings.
https://gitlab.freedesktop.org/plymouth/plymouth/-/issues/154

**Comment by jamacku** [comment]
Thank you for reporting this issue. I have changed the Weblate branch to `main`. Translations should now be unlocked.
